apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
      version: v1
  template:
    metadata:
      labels:
        app: app2
        version: v1
    spec:
      containers:
      - name: app2-poc
        image: myplaceapp2:latest
        volumeMounts:
          - name: secret-volume
            readOnly: true
            mountPath: "/etc/secret-volume"
          - name: config-volume
            readOnly: true
            mountPath: "/etc/config-volume"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "1"
        ports:
        - name: http
          containerPort: 9000
        livenessProbe:
          httpGet:
            path: /management/health
            port: 9000
          initialDelaySeconds: 180
          periodSeconds: 10
          failureThreshold: 20
        readinessProbe:
          httpGet:
            path: /management/health
            port: 9000
          initialDelaySeconds: 180
          periodSeconds: 10
          failureThreshold: 5
      volumes:
        - name: config-volume
          configMap:
            name: config-map2
        - name: secret-volume
          secret:
            secretName: database-creds2