# if the item exists in the yaml
- op: replace
  path: /spec/template/spec/serviceAccount
  value: backend-sa2
# if the item does not exists in the yaml
- op: replace
  path: /spec/template/spec/containers/0/resources
  value: 
          requests:
            memory: "8Gi"
            cpu: "4"
          limits:
            memory: "8Gi"
            cpu: "4"




